spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: NEED_TO_INPUT
          google:
            clientId: NEED_TO_INPUT
            clientSecret: NEED_TO_INPUT
custom:
  jwt:
    secretKey: abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789
  prod:
    database:
      password: 1234
    members:
      system:
        password: NEED_TO_INPUT
      admin:
        password: NEED_TO_INPUT
      garage:
        password: NEED_TO_INPUT`